version: '3.4'

services:
  web1:
    image: webcore  #是指定服务的镜像名称或镜像ID。如果镜像在本地不存在，Compose将会尝试拉取镜像
    container_name: "web1"  #容器名称格式是：<项目名称><服务名称><序号>可以自定义项目名称、服务名称，但如果想完全控制容器的命名，可以使用标签指定
    build: #服务除了可以基于指定的镜像，还可以基于一份Dockerfile，在使用up启动时执行构建任务，构建标签是build，可以指定Dockerfile所在文件夹的路径。Compose将会利用Dockerfile自动构建镜像，然后使用镜像启动服务容器
      context: .  #设定上下文根目录
      dockerfile: WebCore3/Dockerfile  #指定Dockerfile      
  
  nginx1:
    image: nginx
    container_name: nginx1
    ports: 
      - 9090:80
    volumes: 
      - /host_mnt/d/vm-data/volume/nginx_config:/etc/nginx/conf.d/